# Generated by Django 5.2.3 on 2025-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=122)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
